### ISSUE TITLE
Experiment Runner UI Looks strange or is Tiny when I have a VR headset hooked up

### ISSUE THREAD

**Issue by jackbrookes** [BioMotionLab/TUX#12]
As referenced on your site, the cameras will defaults to render to "Both" eyes even in 2D examples, after SteamVR enables Virtual Reality Supported:

https://biomotionlab.github.io/TUX/docs/Troubleshooting

You should be able to fix it with a script like this attached to the Camera:

```cs
    public class CameraDisplayOverride : MonoBehaviour
    {
        
        /// <summary>
        /// Called when the script is loaded or a value is changed in the
        /// inspector (Called in the editor only).
        /// </summary>
        void OnValidate()
        {
            GetComponent<Camera>().stereoTargetEye = StereoTargetEyeMask.None;
        }
    }
```

**Comment by AdamBebko** [comment]
Thank you for the feedback! I'll implement this in the next release. I also found a way to turn off default camera tracking. However, 2020.2 completely changes this behavior, and a lot of other SteamVR things, so I suspect this may require some updates.

**Comment by AdamBebko** [comment]
New version is up with the fix. Thanks again!
