### ISSUE TITLE
Get more responses in the same trial

### ISSUE THREAD

**Issue by Francodibrotsy** [BioMotionLab/TUX#15]
Hi

I'm new on unity and your package. I'm programing a Necker wich change at random times (one trial is the presentation of a modified necker). I have collected the response, but it only allows me to get one response for trial, and I need to record all pressed button in the trial, but I don't know how to set that. How can you do that? Thanks!

**Comment by AdamBebko** [comment]
Hi, Thanks for your interest in bmlTUX! Sorry you're having trouble. Could you go into a bit more detail about the problem you're having? You can write any data out of a trial that you need. 

The simplest output is just a single dependent variable, but you can add any number of dependent variables. You can even store a huge text dump inside a dependent variable (like a JSON object that has been converted to text).

for example you could do: (pseudocode)

List<string> buttonpresses = new List<string>()
if (Input.GetKeyDown(Keycode.Space) {
    buttonpresses.Add("Space");
}

then convert the list to text and save it in a dependent variable.

Let me know if that helps, or perhaps I misunderstood your question.
Adam

**Comment by Francodibrotsy** [comment]
Hi!
I did what you recommended, but I get the next line in the column of the buttonpress variable:

System.Collections.Generic.List`1 [System.String]

This is the code that I have:
![NeckerCode](https://user-images.githubusercontent.com/62441433/106470887-cdb8da00-647f-11eb-8b55-e5df42462b17.png)
 And this is what I get in the experiment log:

![PrintNecker](https://user-images.githubusercontent.com/62441433/106470945-e4f7c780-647f-11eb-9753-9ce3a6a33f33.png)
 What do you think I can do to fix this? Thanks!

**Comment by AdamBebko** [comment]
You're recreating the list each frame, since you're making it in the Update method. So each frame, the list is being wiped out. 

Also, remember that you need to have the "game" window "focused" to register button presses.

Also, to get the presses to be registered in the output csv file for a trial in BML tux, you need to have the code in your trial script. 

Have you watched my tutorials? Check them out, they may give you a better idea how to do it. You can use a coroutine to poll button presses, or use an event system, save them in the list, and then output the list into a dependent variable as a string.

Hope that points you in the right direction.

**Comment by AdamBebko** [comment]
I Have a bit more time now, here's something that may work for you

in your custom trial script:

add a field to store button presses. 

`
            //this is a class-field
            List<string> buttonPresses;
`

In your main Method, you call a new Coroutine function.

`
            //Your main method code
            
            //when you want to listen
            yield return ListenForButtonPresses();
            
            //More main code
`

then you add this coroutine to listen for presses and add them to list

`
       IEnumerator ListenForButtonPresses() {
            
            
            //maybe you want to create this in PreMethod instead
            //if you'll be modifying it in more than one spot
            buttonPresses = new List<string>();
            
            //Listen forever until we're done
            bool listening = true;
            while (listening) {

                if (Input.GetKeyDown(KeyCode.Space)) {
                    buttonPresses.Add("Space");
                }

                if (Input.GetKeyDown(KeyCode.UpArrow)) {
                    buttonPresses.Add("UpArrow");
                }

                //exit (stop listening) if they press return
                if (Input.GetKeyDown(KeyCode.Return)) {
                    break;
                }

                //Let unity take back over, will loop again next frame.
                yield return null;
            }

        }

`

Then in your postmethod, to save to output

`
            // This will create a string like this:
            // Space>UpArrow>Space>Space>UPArrow>
            // In excel you can split this back up later.
            StringBuilder stringBuilder = new StringBuilder();
            foreach (string buttonPress in buttonPresses) {
                stringBuilder.Append($"{buttonPress}>");
            }

            Data["ButtonPresses"] = stringBuilder.ToString();


`

**Comment by AdamBebko** [comment]
Going to close this issue, feel free to let me know if you're still having issues.

**Comment by Francodibrotsy** [comment]
Hi
Sorry for bother you again, but I don't know where I have to write this line:

//Your main method code

//when you want to listen
yield return ListenForButtonPresses();

//More main code


![Script1](https://user-images.githubusercontent.com/62441433/107084901-7182ec80-67d6-11eb-8ffc-d17f6e430b9c.png)
![Script2](https://user-images.githubusercontent.com/62441433/107084907-73e54680-67d6-11eb-8c36-fcfcd1e4f735.png)
![Script3](https://user-images.githubusercontent.com/62441433/107084910-75167380-67d6-11eb-9e10-b535062bcfde.png)
![Script4](https://user-images.githubusercontent.com/62441433/107084915-76e03700-67d6-11eb-96fe-b85cbbdb78a1.png)

I manage to the image change but I can't call the ListenForButtonPresses(). Thanks again for the help!

**Comment by AdamBebko** [comment]
You put the listenforbuttonpresses function inside your maincoroutine function, make it its own function and call it from maincoroutine

**Comment by Francodibrotsy** [comment]
Thanks a lot, finally I was able to run it!
