### ISSUE TITLE
Runner Trial counter wrong

### ISSUE THREAD

**Issue by annethaler** [BioMotionLab/TUX#18]
![IMG_0390](https://user-images.githubusercontent.com/52574589/109045566-be553700-76a1-11eb-8c88-0dffc776f178.jpg)

Trial counter is wrong. Block counter is wrong too!

Screenshot shows trial 39 and is currently in block 2 out of 4.

**Comment by AdamBebko** [comment]
duplicated in #47 , with better info there.
