### ISSUE TITLE
TextMeshPro version requirement

### ISSUE THREAD

**Issue by AlexanderNA** [BioMotionLab/TUX#2]
I've found that using TextMeshPro previews from preview.10 onwards cause text to be misaligned. Tested up to the most recent preview.12. All working fine with preview.8, as in the YouTube tutorial.

**Comment by AdamBebko** [comment]
Thank you for your post. 

This issue is because TextMeshPro for some reason no longer carries over font size in prefabs.

I've been working on a work-around that now looks stable,  and I will pushing a new release this afternoon.  Stay tuned. 
Please let me know if you encounter any more errors.
