### ISSUE TITLE
Send lpt signals through parallel port

### ISSUE THREAD

**Issue by Francodibrotsy** [BioMotionLab/TUX#41]
I need to send triggers signals to an EEG device through a parallel port every time a stimulus appears in the VR.  How can I do this in the bmltux environment? 

Greetings!

**Comment by AdamBebko** [comment]
I have no idea! But BmlTUX is compatible with any c# code. So if you can do it in C# you can do it in bmlTUX. Sorry I can’t be of more help. If you run into any specific BmlTUX questions feel free to reach out again. 

Adam
