### ISSUE TITLE
Feature Request: Console Message Colors

### ISSUE THREAD

**Issue by A-Ivan** [BioMotionLab/TUX#45]
Some of the font colors used to show messages in the console make it difficult to read the message. 

It would be great if there were an option to default all the colors to a specific color so if the user has difficulty to read the message because of the colored font, a specific color (like white) could be used. Maybe in the Settings file there could be an option to use either the default colored messages or to use a specific color (where the use could either choose from a list of pre-defined options or use a color picker to choose a color).

Here is an example of a message with a font that is difficult to read (at least to me).

![image](https://user-images.githubusercontent.com/17125077/148620030-e20cc7e7-e510-49c4-8b83-d9c09c4229c1.png)

**Comment by AdamBebko** [comment]
Included in next version. Settings in project settings

![Screen Shot 2022-02-13 at 2 21 22 PM](https://user-images.githubusercontent.com/43276915/153771120-055138ea-4253-4ece-b87f-b35fd1cc2999.png)

Autogenerated here:  The weird character at the front is to sort it last in the assets folder to keep it out of the way.

![Screen Shot 2022-02-13 at 2 22 00 PM](https://user-images.githubusercontent.com/43276915/153771138-572f144d-6110-479a-b5c9-a19b7d640f0c.png)
