### ISSUE TITLE
Feature Request: Block, TrialInBlock, Trial Numbering Starting From 1 Instead of 0

### ISSUE THREAD

**Issue by A-Ivan** [BioMotionLab/TUX#47]
It would be great to have the option of setting if the Block, TrialInBlock, and Trial Numbers start from either 0 or 1. Maybe this could be in the Settings file. Starting from 1 could be less confusing then starting from 0. Internally in the background code it does not matter if it is 0 or 1, but showing these as starting from 1 in the preview table/GUI and in the output file makes things easier when understanding/processing the data.

**Comment by AdamBebko** [comment]
due to being in maintenance mode, unfortunately this will not be added in the forseable future
