### ISSUE TITLE
Custom Design File - Default Columns and File Location

### ISSUE THREAD

**Issue by DerMilchmann** [BioMotionLab/TUX#56]
**Default Columns**
I am currently replicating a real life Experiment in VR and my peers working on the real life Experiment are sending me the Trial Table which should also be used for the VR Experiment. But the BML_TUX Framework requires certain Columns to be included in the Design File which I dont need:

- Completed
- Attempts
- Skipped
- TrialTime

Is there any way to exclude those default Columns? Right now I am modifying the Design File before and after the VR-Experiments and it would save me some time if I could just disable the default Columns.

**File Location**
Output files either take a full path or is relative to the MyDocuments folder. The Design File Location can also take a full path or searches relative to the root folder of the Application, which is inconsistent in my opinion.
Also unlike output files, the Custom Design Input Field doesnt have a Validator and it crashes instead of throwing a nice error popup.

A way to quickly fix this would be to create a DesignFileValidationResult and add it to the validators in the SessionSetupPanel.
I've never done a Pull Request before, but tried #55

**Comment by AdamBebko** [comment]
included
