### ISSUE TITLE
PackageInfo causes compile errors

### ISSUE THREAD

**Issue by DerMilchmann** [BioMotionLab/TUX#6]
Hey,

I was trying to build my Unity Project and got the following compile error:

`Library\PackageCache\com.biomotionlab.tux@14dec42edd\Scripts\UI\RuntimeUI\ExperimentGui.cs(16,33): error CS0234: The type or namespace name 'PackageManager' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`

-bmlTUX Version 0.17.3.
-TextMeshPro 2.1.0 preview.8
-Tested in Editor Versions 2019.3.13f1 and 2019.3.15f1
-API Compatibility Level is set to .Net 4.x.
Deleting the Package Folder to let Unity rebuild it didnt resolve the issue.

Removing the following line in ExperimentGui.cs let me build my Project:
`using PackageInfo = UnityEditor.PackageManager.PackageInfo;`

To use your package I upgraded and existing Project from 2018.2.20f1.

I hope I could provide you with enough information to find the issue.

**Comment by AdamBebko** [comment]
Thank you, this fix will be in the next release. Please let me know if you run into more problems.

**Comment by AdamBebko** [comment]
version 0.17.4 is now live, it should fix this bug.
