### ISSUE TITLE
How to Log Custom Continuous Data?

### ISSUE THREAD

**Issue by A-Ivan** [BioMotionLab/TUX#60]
Not sure if I missed this in the documents, but is there a way to continuously log information during a trial?

For instance, in a trial, every time a specific event (i.e., specific function call) occurs (could occur 1 to 20 times in each trial) I would like to log some information (i.e., time since the trial has began, and some custom floats and strings data). This information to log would be different than the information logged on the trial level, it would be a separate csv output where each row would be each time a relevant event (one I am interested in logging) occurred.

I think this would be similar to how continuous game object tracking information is logged, but the logging would be of other data types and would occur only when specific events occur.

In my study, trials contain a series of tasks. I want to log when those tasks are completed, when/what type of error occurred, etc. The trial level data would contain information (dependent variables) like when the trial finished (once all tasks are completed), number of errors (specific user actions I deem as errors) for each error type, etc.

Thank you.

**Comment by AdamBebko** [comment]
New docs about to be released. See Continuous data section in documentation.

**Comment by A-Ivan** [comment]
Hi @AdamBebko 
How/where can I find this documentation?
I normally read it on the biomotionlab's [website](https://biomotionlab.github.io/TUX/), but I do not see the Continuous data section there. Would it be [here](https://github.com/BioMotionLab/TUX/blob/master/doc_projects/docs/Continuous-data.md), in the docs folder of this repository?

**Comment by AdamBebko** [comment]
Oops. I forgot to publish the updated website!!! Derp! 🤪 will do that this evening.

**Comment by AdamBebko** [comment]
But yes that is the correct document.

**Comment by A-Ivan** [comment]
Great, I'll wait for the website update, easier to read there :)
