### ISSUE TITLE
Continuous Data Logging Issues

### ISSUE THREAD

**Issue by A-Ivan** [BioMotionLab/TUX#63]
I was looking at the [documentation](https://biomotionlab.github.io/TUX/docs/ContinuousData) on logging continuous data and I have some questions about the Recorder Example Scene provided:

1. Is there a way to only set the output folder but not the playback one if I only want to log data? If I only want to log continuous data but not play it back (removing or disabling the Playback Manager script), the following error appears:
 
"
No directory  
UnityEngine.Debug:LogError (object,UnityEngine.Object)
bmlTUX.Recorder.RecordableComponent`1<bmlTUX.Recorder.TransformSnapshotBase>:InitializeFile () (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordableComponent.cs:40)
bmlTUX.Recorder.RecordableComponent`1<bmlTUX.Recorder.TransformSnapshotBase>:SaveSnapshotToCsv (single,int) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordableComponent.cs:53)
bmlTUX.Recorder.RecordableComponent`1<bmlTUX.Recorder.TransformSnapshotBase>:CreateSnapShot (single,int) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordableComponent.cs:32)
bmlTUX.Recorder.Recorder:UpdateRecording (single,int) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/Recorder.cs:82)
bmlTUX.Recorder.RecordingManager:FixedUpdate () (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordingManager.cs:130)
"

"
ArgumentNullException: Value cannot be null.
Parameter name: path
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string,bool)
System.IO.File.AppendAllText (System.String path, System.String contents) (at <695d1cc93cca45069c528c15c9fdd749>:0)
bmlTUX.Recorder.RecordableComponent`1[T].SaveSnapshotToCsv (System.Single time, System.Int32 frame) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordableComponent.cs:56)
bmlTUX.Recorder.RecordableComponent`1[T].CreateSnapShot (System.Single time, System.Int32 frame) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordableComponent.cs:32)
bmlTUX.Recorder.Recorder.UpdateRecording (System.Single time, System.Int32 frame) (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/Recorder.cs:82)
bmlTUX.Recorder.RecordingManager.FixedUpdate () (at Library/PackageCache/com.biomotionlab.tux@3.0.0/Extras/Recorder/Scripts/RecordingManager.cs:130)
"

2. In the Recording Manager script, if I set the Output Folder via the editor before I play the scene, when I enter play mode the Output folder I had set becomes empty, giving errors which require me to set the folder again. It would be great if the folder set via the Unity editor were to maintained during play mode. Not sure if this occurs because the ReocrderManager prefab and the Recording Manager script are in the package folder (read-only), but this shouldn't be the issue.

3. Is there a way to automatically set the output folder of the continuous data to be the same folder as the output data files from the experiment (participant trial/block output)?

4. Does the continuous data recording work also when the project is built to an executable? Since the output folder seems to be cleared when executed I imagine there might be a problem there as well.

Thank you.

**Comment by AdamBebko** [comment]
I think you can solve this if you just copy and paste the same path into the playback path. This is probably a bug though I will look into this.


Dr. Adam O. Bebko, Ph.D.
***@***.***
adambebko.com
