### ISSUE TITLE
"2 event systems in the scene"

### ISSUE THREAD

**Issue by xywang01** [BioMotionLab/TUX#65]
Hi Adam

After updating to v3.0.1, Unity will start complaining about the following:

"There are 2 event systems in the scene. Please ensure there is always exactly one event system in the scene
UnityEngine.EventSystems.EventSystem:Update ()".

This message would disappear if I were to disable either the experiment runner object or the SteamVR Player object. 

![image](https://user-images.githubusercontent.com/15709552/159719623-34a1ed7a-7e81-4ce2-9f09-a320e675cdd4.png)

This does not affect the execution of the experiment; rather, it just produces thousands of warnings. Is this something that others also experience? Thanks!

**Comment by AdamBebko** [comment]
This is a common unity issue, not related to bmlTUX. It means you have two event system components somewhere in the scene. You can use Unity’s search tools to help diagnose the problem. You only need one ever. They collect input events from the user, and shouldn’t be collected twice. You should keep the event system that is the “longest lived” in the scene. So if one is attached to a game object that won’t survive the whole scene, maybe delete it, and create a new one at the root of your scene that lasts for the lifetime of your scene.

**Comment by xywang01** [comment]
For those of you who encounter a similar issue, this is due to the conflict between bmlTUX and SteamVR's InputModule. To stop the warnings from spamming your Console, you may consider disabling the Event System in SteamVR's Player prefab. 

YOu can find the attached Event System through:
Player -> InputModule -> Event System
![image](https://user-images.githubusercontent.com/15709552/159802328-d75adf5b-db5e-4d2e-b846-16fcb31c42e9.png)

I am not sure about the repercussions of disabling SteamVR's event system, but it might potentially affect using the UI component of SteamVR.

**Comment by AdamBebko** [comment]
Just a reminder that you can provide your own GUI Prefab to the design file via settings. So you can copy my prefab, remove the event system, and point the design file to this new prefab, allowing you to use the SteamVR one if you prefer.

Adam

**Comment by AdamBebko** [comment]
Another option is to make a script  with FindObjectsOfType<EventSystem>. And then disable all but one.
