### ISSUE TITLE
Adding Independant Bool Value throws OutOfBounds Exception

### ISSUE THREAD

**Issue by DerMilchmann** [BioMotionLab/TUX#7]
Steps to reproduce:
1. Add independant boolean variable
2. Add a Value (+)

Full Error Message from the Unity Editor:
`Retrieving array element that was out of bounds
UnityEditor.SerializedProperty:InsertArrayElementAtIndex(Int32)
bmlTUX.Scripts.VariableSystem.VariableUI.VariableViewer:AddPlusButton() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/VariableViewer.cs:242)
bmlTUX.Scripts.VariableSystem.VariableUI.VariableViewer:DisplayValues() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/VariableViewer.cs:225)
bmlTUX.Scripts.VariableSystem.VariableUI.VariableViewer:AddIndependentVariableValueProperties() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/VariableViewer.cs:180)
bmlTUX.Scripts.VariableSystem.VariableUI.VariableViewer:AddIndependentVariableProperties() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/VariableViewer.cs:165)
bmlTUX.Scripts.VariableSystem.VariableUI.VariableViewer:Show() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/VariableViewer.cs:52)
bmlTUX.Scripts.VariableSystem.VariableUI.ExperimentDesignFileEditor:ShowViewers(List1) (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/ExperimentDesignFileEditor.cs:238)
bmlTUX.Scripts.VariableSystem.VariableUI.ExperimentDesignFileEditor:ShowVariableFactory() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/ExperimentDesignFileEditor.cs:188)
bmlTUX.Scripts.VariableSystem.VariableUI.ExperimentDesignFileEditor:OnInspectorGUI() (at D:/DronenExperiment-bmlTUX/Library/PackageCache/com.biomotionlab.tux@14dec42edd/Scripts/VariableSystem/VariableUI/ExperimentDesignFileEditor.cs:130)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

Similiar Error Messages occur when you try to switch a Independant Boolean Variable from the "Balanced" mixing type to "Custom Probability"

**Comment by AdamBebko** [comment]
Thanks again for the bug report. It's now fixed, and up and running (new version 0.17.5)

To install:

In Unity Package Manager, Add from git:
https://github.com/BioMotionLab/TUX.git#1.0.0
