### ISSUE TITLE
Missing files upon reopening experiment project

### ISSUE THREAD

**Issue by ggoldin164** [BioMotionLab/TUX#70]
I've been working on an experiment that uses the BML TUX platform for about a year, and about a week ago, just before starting data collection, I started experiencing the following error upon trying to start the experiment: 

<img width="1199" alt="image" src="https://github.com/BioMotionLab/TUX/assets/137097736/8806ccb1-390a-4976-a3be-2cd25229d4e6">

To me, there seems to have been some data loss in the form of missing scripts or other files, although I am not totally sure if that is the main issue. Looking across different experiment iterations in my project hub gives the same error. I was hoping someone could lead me in the right direction to find out how to resolve this error, perhaps by how I can go about retrieving the necessary files. 

Not sure if this is helpful, but I noticed this error after my laptop ran out of battery in the middle of a session. I could understand how this would lead to some data loss, but if that's the case, I'm not sure why data loss on one experiment affects all of my experiments, nor do I understand how to go about replacing those missing files. If anyone can help, I would extremely appreciate it this way I can start running data collection on my experiment!

**Comment by AdamBebko** [comment]
I would recommend the following:

not looks like the error has to do with the editorsettings file or script. Make sure the file is still in your project and make sure that the editorsettings script is there. 

If that seems to be the problem try to restore your editorsettings from your version control. 


If I editorsettings looks good:

First thing to do is to check previous versions of your project in version control and see when it broke. 

If that doesn’t work, try closing Unity, deleting the library folder, then reopening Unity

If that doesn’t work, try a fresh clone of your project. (Delete whole folder and re-clone from version control)

Reinstall Unity. 

If none of those work try sending me your project somehow and I can try to take a quick look!

hope that helps!
Adam

**Comment by AdamBebko** [comment]
Fixed in https://github.com/BioMotionLab/TUX/pull/73
